# This workflow is needed for when the automated CD workflow failed to deploy,
# and the bugfix will not trigger it.
name: Build & Push Docker Image (Manually Triggered)

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: anthonydickson/budgeteur

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest

    outputs:
      semver: ${{ steps.version.outputs.semver }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: Cargo.toml
          sparse-checkout-cone-mode: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Read Version from Cargo.toml
        id: version
        run: |
          VERSION=$(python -c 'import tomllib; f = open("Cargo.toml", "rb"); print(tomllib.load(f)["package"]["version"])')
          echo "semver=${VERSION}" >> "${GITHUB_OUTPUT}"
          echo "${VERSION}"

                    
  enforce-unique-tag:
    name: Enforce Unique Image Tag
    runs-on: ubuntu-latest
    needs: get-version

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if tag exists
        id: tag-check
        run: |
          RESULT=$(docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.get-version.outputs.semver }} 2>&1 || exit_code=$?)

          if [[ -n $exit_code && $RESULT != "manifest unknown" ]]; then
            echo "❗Error $exit_code: $RESULT"
            exit 1
          fi

          if [ "$RESULT" != "manifest unknown" ]; then
            echo "🚨 Tag already exists, update the version in Cargo.toml! 🚨"
            exit 1
          fi

          echo "✅ Tag is unique, proceeding with build"

  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - get-version
      - enforce-unique-tag

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.get-version.outputs.semver }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate Artifact Attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

# TODO: Once stable (1.0.0), tag image twice, once with full semver and
# again with the major version. This will allow me to pin to a major version
# on my NAS and have it download updates with a single click.
